### PR TITLE
bugfixes

### PR DESCRIPTION
**Pull request by subzer047**

### CODE REVIEW

**Comment by hiro-git-hub** [comment]
Hello, I'm trying to use this EmzBiancoTheme with different variant articles, but it seems, that this won't work. Have you ever recognized a similar bug? Best regards

**Comment by subzer047** [comment]
Hi hiro, I've checked the variant articles and it isn't fixed yet.

I'm going to fix this in the next few days. Thanks for your comment. If you find anything else feel free to create an issue for this repository.
Greets

**Comment by hiro-git-hub** [comment]
Perfect, thank you. I also found an error with stripe plugin. The input fields for credit card payments will not be created. Seems like an javascript problem. I will create an issue.

**Comment by subzer047** [comment]
The Variants are now fixed. I'm actually working on the paypal plugin compability. I'm gonna check out the stripe problem after that. 
Greets
subzero

**Pull request merged**
